### ISSUE TITLE
Create annotations 

### ISSUE THREAD

**Issue by graphefruit** [gearit/RadaeePDF-Cordova#10]
Hi @NermeenSolaiman,

I'm just trying this plugin because it looks like a real good solution, but I'm searching for the possibility that the user can create annotations, mark text or something like this.
Like written here:
http://www.radaeepdf.com/download/cordova-plugin

Can you give me a hint/solution how to use it in JavaScript?
Thanks so far
Graphefruit

**Comment by NermeenSolaiman** [comment]
Hi,
Unfortunatelly, these features is currently not available on JS level (and is not planned to be added in the next releases).
For that reason the native Java & iOS source code are included.

You can open a ticket in the [support tickets area](http://www.radaeepdf.com/support/tickets) addressed to (RadaeePDF Sales) as handler, and ask for these feature.

**Comment by graphefruit** [comment]
Thanks for the fast respone!
I need to evaluate, sad this is not existing else this would be a perfect plugin for us.
Greetings
Graphefruit

**Comment by NermeenSolaiman** [comment]
It's just not exposed in JS, but they are already implemented in the available plugin (from the top toolbar)

**Comment by graphefruit** [comment]
Hi @NermeenSolaiman,

Maybe to clearify the situation, if you show the PDF by the javascript call, an overlay will be created which will then be added on top.
Now can the JS interact with this sheet or not.
If not therefore it would need to be implemented in native code to create a new annotation with an overlay where the keyboard shows up, or to mark the text in yellow or something like this (colorpicker e.g.).

If it would be accessable in javascript, this would be the same way, but it would be written in JS.

So is statement 1 or 2 truth?

If statement 1 is true, it wouldn't make any sense to expose it in JS, because you couldn't access it.
Thanks so far

**Comment by NermeenSolaiman** [comment]
No, it's not possible. 

If you are really interested, you can write to Sales, and they will evaluate the feasibility of such a feature.

**Comment by graphefruit** [comment]
Yes I'm realy interested but I just got a deadline until tomorrow, and then it needs to be discussed and the deadline need to be set.

I'll wait until tomorrow and the outcome and then maybe reach out to the sales team.
Thank you that far 👍

**Comment by MarKco** [comment]
Hello,
now I see on http://www.radaeepdf.com/download/cordova-plugin the following:
"create and modify annotations within the full UI (free hand, rectangle, circle, arrow, text,etc)"

Does this mean that the annotation framework was added to the cordova library as well?

**Comment by NermeenSolaiman** [comment]
No they are not exposed in JS, they are already implemented in native Android and iOS.

If you are interested in these features, you can open a ticket in the[ support tickets area ](http://www.radaeepdf.com/support/tickets)addressed to (RadaeePDF Sales) as handler, and ask for these features.
