### ISSUE TITLE
Cordova plugin installation takes forever

### ISSUE THREAD

**Issue by hamidfzm** [gearit/RadaeePDF-Cordova#16]
I try installing the plugin on empty Cordova project using the following command:

```bash
>> cordova plugin add https://github.com/gearit/RadaeePDF-Cordova.git --save --verbose
No scripts found for hook "before_plugin_add".
Calling plugman.fetch on plugin "https://github.com/gearit/RadaeePDF-Cordova.git"
fetch: Installing https://github.com/gearit/RadaeePDF-Cordova.git to /Users/hamidfzm/Projects/test-cordova
Running command: npm install https://github.com/gearit/RadaeePDF-Cordova.git --production --save-exact
```

But it takes forever and nothing happens. By the way, I'm using Cordova 9.0.0 with Android platform 8.0.0.

**Comment by NermeenSolaiman** [comment]
We have tried using the same configuration (cordova 9 and Android 8), and there was no problem.
![install](https://user-images.githubusercontent.com/8235196/59303308-38f3de00-8c96-11e9-8fb1-a6e521812c06.png)

**Comment by hamidfzm** [comment]
Thanks, I think my slow internet connection and large repository size were causing this issue. I cloned the repo and installed the plugin locally. It works perfectly.
