### ISSUE TITLE
Thumbnails link

### ISSUE THREAD

**Issue by parcle** [gearit/RadaeePDF-Cordova#18]
Hi,
if you tap thumbnails it doesn't reach the correct page but random one.
I',ve standard license with last version installed

**Comment by NermeenSolaiman** [comment]
Which view mode are you using?

We've checked and it seems to work correctly.

**Comment by parcle** [comment]
RadaeePDFPlugin.setReaderViewMode(
              {
                  mode: 3 //0:vertical 3:single 4:dual 6:Dual with cover(1st page single)
              },
              function(message){
                  console.log("Success: " + message);
              },
              function(err){
                  console.log("Failure: " + err);
              });

**Comment by NermeenSolaiman** [comment]
We've checked with single and dual modes and cannot reproduce the issue.

Make sure that all classes under com.radaee.view are updated to latest version.

**Comment by parcle** [comment]
The issue is on ios version and reproducible also on your demo package , here is the steps 

1) cordova create RadaeePDF-Cordova com.radaee.pdf.PDFViewer RadaeePDF-Cordova
2)cordova platform add ios --save
3)cordova plugin add https://github.com/gearit/RadaeePDF-Cordova.git --save
4)copy demo folder on www
5)cordova build ios
6)open on xcode and build from there to my device (iPhone 8 + iOs 13.3.1) xCode 11.3.1

**Comment by NermeenSolaiman** [comment]
Fixed with latest commit https://github.com/gearit/RadaeePDF-Cordova/commit/21515bef6b10fb7693cca27a45bc6593adec3c45
