### ISSUE TITLE
Cannot Build, Run or emulate Android 

### ISSUE THREAD

**Issue by dementorpasha** [gearit/RadaeePDF-Cordova#2]
I have problems when try build or run emulate android application.

> Error: /srv/http/reader/cordova-0.13_RadaeePDF/platforms/android/gradlew: Command failed with exit code 1 Error output:
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> /srv/http/reader/cordova-0.13_RadaeePDF/platforms/android/src/com/radaee/reader/PDFPagerAct.java:64: error: package R does not exist
>         m_pager = (PDFViewPager)m_layout.findViewById(R.id.pdf_pager);
>                                                        ^
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 1 error
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by NermeenSolaiman** [comment]
Did you apply the command `cordova build android`?, this command is responsible for executing **configure-android.js** that should fix this import error

**Comment by dementorpasha** [comment]
I understand, I should use  `cordova create RadaeePDF-Cordova com.radaee.reader RadaeePDF-Cordova` or change namespace.
