### ISSUE TITLE
Can not build for Android

### ISSUE THREAD

**Issue by Tankwacht** [gearit/RadaeePDF-Cordova#5]
Without this plugin everything worked fine, but i cant compile anymore when the plugin is added.
I've already tried removing and re-adding the plugin and the platform. Somebody has an Idea?

    $ cordova build android
    BUILD FAILED

    Total time: 2.263 secs
    Error: /Users/user/git Repositories/epaper/platforms/android/gradlew: Command failed with exit code 1 Error output:
    /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/util/RadaeePDFManager.java:11: error: cannot find symbol
    import com.radaee.reader.R;
                            ^
      symbol:   class R
      location: package com.radaee.reader
    /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/reader/PDFPagerAct.java:15: error: cannot find symbol
    import com.radaee.reader.R;
                            ^
      symbol:   class R
      location: package com.radaee.reader
    /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/util/RadaeePDFManager.java:86: error: package R does not exist
                Toast.makeText(context, context.getString(R.string.failed_invalid_path), Toast.LENGTH_SHORT).show();
                                                           ^
    /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/reader/PDFPagerAct.java:64: error: package R does not exist
            m_layout = (RelativeLayout) LayoutInflater.from(this).inflate(R.layout.pdf_fragment, null);
                                                                           ^
    /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/reader/PDFPagerAct.java:65: error: package R does not exist
            m_pager = (PDFViewPager)m_layout.findViewById(R.id.pdf_pager);
                                                           ^
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    5 errors

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':compileDebugJavaWithJavac'.
    > Compilation failed; see the compiler error output for details.

Complete log:

    $ cordova build android

    Running command: "/Users/user/git Repositories/epaper/hooks/after_prepare/010_add_platform_class.js" "/Users/user/git Repositories/epaper"
    add to body class: platform-android
    *****************************************
    *       inject file R  ANDROID             *
    *****************************************
    *       Inject: com.exmaple.epaper.R    *
    *  Inject in file: /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/pdf/Global.java the import statemet: com.radaee.viewlib.R  *
    *  Inject in file: /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/reader/PDFLayoutView.java the import statemet: com.radaee.viewlib.R  *
    *  Inject in file: /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/reader/PDFNavAct.java the import statemet: com.radaee.viewlib.R  *
    *  Inject in file: /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/reader/PDFViewAct.java the import statemet: com.radaee.viewlib.R  *
    *  Inject in file: /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/reader/PDFViewController.java the import statemet: com.radaee.viewlib.R  *
    *  Inject in file: /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/util/OutlineListAdt.java the import statemet: com.radaee.viewlib.R  *
    *  Inject in file: /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/util/PDFGridItem.java the import statemet: com.radaee.viewlib.R  *
    *  Inject in file: /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/util/PopupEditAct.java the import statemet: com.radaee.viewlib.R  *
    *  Inject in file: /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/util/CommonUtil.java the import statemet: com.radaee.viewlib.R  *
    Attempting to set app name
    Setting App Name:  ePaper
    Processing settings for platform: android
    Wrote AndroidManifest.xml: /Users/user/git Repositories/epaper/platforms/android/AndroidManifest.xml
    Processing settings for platform: ios
    Wrote iOS Plist: /Users/user/git Repositories/epaper/platforms/ios/ePaper/ePaper-Info.plist
    ANDROID_HOME=/Users/user/Library/Android/sdk
    JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
    Reading build config file: /Users/user/git Repositories/epaper/build.json
    Incremental java compilation is an incubating feature.
    :preBuild UP-TO-DATE
    :preDebugBuild UP-TO-DATE
    :checkDebugManifest
    :CordovaLib:preBuild UP-TO-DATE
    :CordovaLib:preDebugBuild UP-TO-DATE
    :CordovaLib:compileDebugNdk UP-TO-DATE
    :CordovaLib:compileLint
    :CordovaLib:copyDebugLint UP-TO-DATE
    :CordovaLib:mergeDebugProguardFiles UP-TO-DATE
    :CordovaLib:packageDebugRenderscript UP-TO-DATE
    :CordovaLib:checkDebugManifest
    :CordovaLib:prepareDebugDependencies
    :CordovaLib:compileDebugRenderscript UP-TO-DATE
    :CordovaLib:generateDebugResValues UP-TO-DATE
    :CordovaLib:generateDebugResources UP-TO-DATE
    :CordovaLib:packageDebugResources UP-TO-DATE
    :CordovaLib:compileDebugAidl UP-TO-DATE
    :CordovaLib:generateDebugBuildConfig UP-TO-DATE
    :CordovaLib:mergeDebugShaders UP-TO-DATE
    :CordovaLib:compileDebugShaders UP-TO-DATE
    :CordovaLib:generateDebugAssets UP-TO-DATE
    :CordovaLib:mergeDebugAssets UP-TO-DATE
    :CordovaLib:processDebugManifest UP-TO-DATE
    :CordovaLib:processDebugResources UP-TO-DATE
    :CordovaLib:generateDebugSources UP-TO-DATE
    :CordovaLib:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
    :CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
    :CordovaLib:processDebugJavaRes UP-TO-DATE
    :CordovaLib:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
    :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
    :CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
    :CordovaLib:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
    :CordovaLib:transformNative_libsWithSyncJniLibsForDebug UP-TO-DATE
    :CordovaLib:bundleDebug UP-TO-DATE
    :prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
    :preReleaseBuild UP-TO-DATE
    :CordovaLib:preReleaseBuild UP-TO-DATE
    :CordovaLib:compileReleaseNdk UP-TO-DATE
    :CordovaLib:copyReleaseLint UP-TO-DATE
    :CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
    :CordovaLib:packageReleaseRenderscript UP-TO-DATE
    :CordovaLib:checkReleaseManifest
    :CordovaLib:prepareReleaseDependencies
    :CordovaLib:compileReleaseRenderscript UP-TO-DATE
    :CordovaLib:generateReleaseResValues UP-TO-DATE
    :CordovaLib:generateReleaseResources UP-TO-DATE
    :CordovaLib:packageReleaseResources UP-TO-DATE
    :CordovaLib:compileReleaseAidl UP-TO-DATE
    :CordovaLib:generateReleaseBuildConfig UP-TO-DATE
    :CordovaLib:mergeReleaseShaders UP-TO-DATE
    :CordovaLib:compileReleaseShaders UP-TO-DATE
    :CordovaLib:generateReleaseAssets UP-TO-DATE
    :CordovaLib:mergeReleaseAssets UP-TO-DATE
    :CordovaLib:processReleaseManifest UP-TO-DATE
    :CordovaLib:processReleaseResources UP-TO-DATE
    :CordovaLib:generateReleaseSources UP-TO-DATE
    :CordovaLib:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
    :CordovaLib:compileReleaseJavaWithJavac UP-TO-DATE
    :CordovaLib:processReleaseJavaRes UP-TO-DATE
    :CordovaLib:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
    :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
    :CordovaLib:mergeReleaseJniLibFolders UP-TO-DATE
    :CordovaLib:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
    :CordovaLib:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
    :CordovaLib:bundleRelease UP-TO-DATE
    :prepareHockeySDK413Library UP-TO-DATE
    :prepareDebugDependencies
    :compileDebugAidl UP-TO-DATE
    :compileDebugRenderscript UP-TO-DATE
    :generateDebugBuildConfig UP-TO-DATE
    :mergeDebugShaders UP-TO-DATE
    :compileDebugShaders UP-TO-DATE
    :generateDebugAssets UP-TO-DATE
    :mergeDebugAssets UP-TO-DATE
    :generateDebugResValues UP-TO-DATE
    :generateDebugResources UP-TO-DATE
    :mergeDebugResources UP-TO-DATE
    :processDebugManifest UP-TO-DATE
    :processDebugResources UP-TO-DATE
    :generateDebugSources UP-TO-DATE
    :incrementalDebugJavaCompilationSafeguard UP-TO-DATE
    :compileDebugJavaWithJavac
    :compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
    /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/util/RadaeePDFManager.java:11: error: cannot find symbol
    import com.radaee.reader.R;
                            ^
      symbol:   class R
      location: package com.radaee.reader
    /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/reader/PDFPagerAct.java:15: error: cannot find symbol
    import com.radaee.reader.R;
                            ^
      symbol:   class R
      location: package com.radaee.reader
    /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/util/RadaeePDFManager.java:86: error: package R does not exist
                Toast.makeText(context, context.getString(R.string.failed_invalid_path), Toast.LENGTH_SHORT).show();
                                                           ^
    /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/reader/PDFPagerAct.java:64: error: package R does not exist
            m_layout = (RelativeLayout) LayoutInflater.from(this).inflate(R.layout.pdf_fragment, null);
                                                                           ^
    /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/reader/PDFPagerAct.java:65: error: package R does not exist
            m_pager = (PDFViewPager)m_layout.findViewById(R.id.pdf_pager);
                                                           ^
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    5 errors
    :compileDebugJavaWithJavac FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':compileDebugJavaWithJavac'.
    > Compilation failed; see the compiler error output for details.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    BUILD FAILED

    Total time: 2.263 secs
    Error: /Users/user/git Repositories/epaper/platforms/android/gradlew: Command failed with exit code 1 Error output:
    /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/util/RadaeePDFManager.java:11: error: cannot find symbol
    import com.radaee.reader.R;
                            ^
      symbol:   class R
      location: package com.radaee.reader
    /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/reader/PDFPagerAct.java:15: error: cannot find symbol
    import com.radaee.reader.R;
                            ^
      symbol:   class R
      location: package com.radaee.reader
    /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/util/RadaeePDFManager.java:86: error: package R does not exist
                Toast.makeText(context, context.getString(R.string.failed_invalid_path), Toast.LENGTH_SHORT).show();
                                                           ^
    /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/reader/PDFPagerAct.java:64: error: package R does not exist
            m_layout = (RelativeLayout) LayoutInflater.from(this).inflate(R.layout.pdf_fragment, null);
                                                                           ^
    /Users/user/git Repositories/epaper/platforms/android/src/com/radaee/reader/PDFPagerAct.java:65: error: package R does not exist
            m_pager = (PDFViewPager)m_layout.findViewById(R.id.pdf_pager);
                                                           ^
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    5 errors

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':compileDebugJavaWithJavac'.
    > Compilation failed; see the compiler error output for details.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by NermeenSolaiman** [comment]
You need to Replace all occurrences of com.radaee.reader.R with your.app.packagename.R (com.exmaple.epaper.R)

**Comment by Tankwacht** [comment]
Replaced it in the following files:

    configure-android.js
    src/android/ViewLib/src/main/java/com/radaee/reader/PDFPagerAct.java
    src/android/ViewLib/src/main/java/com/radaee/util/RadaeePDFManager.java

After that compiling worked

**Comment by NermeenSolaiman** [comment]
The plugin has been updated to include these files.
Thanks

**Comment by Stefano1964** [comment]
Hi, instead of com.radaee.reader.R you have com.radaee.viewlib.R, in order to build you have to manually change it in a lot of java files...

**Comment by NermeenSolaiman** [comment]
**configure-android.js** already does that (Replace all occurrences of com.radaee.viewlib
.R with your.app.packagename.R
), you need to run (**cordova build android**) to execute this file.
