### ISSUE TITLE
 Can't add plugin, wrong version number

### ISSUE THREAD

**Issue by titanlizard** [gearit/RadaeePDF-Cordova#7]
Following error occurs during `cordova plugin add` command:

Error: Failed to fetch plugin https://github.com/gearit/RadaeePDF-Cordova.git vi
a registry. Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! Invalid version: "1.0"

It seems that version number in package.json differs from plugin.xml.

**Comment by NermeenSolaiman** [comment]
This has been fixed, please try again
