### ISSUE TITLE
Expose listener to javascript interface

### ISSUE THREAD

**Issue by Stefano1964** [gearit/RadaeePDF-Cordova#9]
Hi, i see there are listeners in RadaeePDFPlugin.java, for example willCloseReader(), but there is no cordova callback, it's todo or we have to implement it. We need this in both Android and iOS, otherwise when/how we can test if a pdf doc is saved or not with RadaeePDFPlugin.getFileState()?

**Comment by NermeenSolaiman** [comment]
No they are not todo, you can implement it the way that suites your requirements.
If you have a better suggestion, feel free to share it, we will evaluate the possibility to add it to our plan.

**Comment by NermeenSolaiman** [comment]
We have introduced the callbacks on js level, for more info please check [http://www.radaeepdf.com/support/knowledge-base?view=kb&kbartid=84](http://www.radaeepdf.com/support/knowledge-base?view=kb&kbartid=84)
